version: '2'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123qwerty
      MYSQL_USER: user
      MYSQL_PASSWORD: qwerty123

  smtp:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  project.fpm:
    build:
      context: ./
      dockerfile: fpm.dockerfile
    volumes:
      - ./../:/var/www/html
    environment:
      HOST: localhost
      DB_HOST: mysql
      DB_NAME: test_project
      DB_USER: user
      DB_PASSWORD: qwerty123
      SMTP_HOST: smtp
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      NEWS_RSS: https://www:tvnet:lv/rss/
    links:
      - mysql
      - smtp

  project.localhost:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./../:/var/www/html
    links:
      - project.fpm:phpfpm
